### ISSUE TITLE
Uploading files leads to 400 - Bad request

### ISSUE THREAD

**Issue by igorquintaes** [calico-crusade/mangadex-sharp#3]
Currently when we try to upload a file ([example](https://github.com/calico-crusade/mangadex-sharp/blob/482cde8a2d5fdb865240991022996b5843d98e96/src/MangaDexSharp/MangaDexUploadService.cs#L118)), we receive a Bad Request error: 

```
<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n
```

The lib is also unable to parse and return it properly because the response is not a json. After some futher investigation, I found some missing configuration (tested [here](https://github.com/calico-crusade/mangadex-sharp/blob/482cde8a2d5fdb865240991022996b5843d98e96/src/MangaDexSharp/MangaDexUploadService.cs#L118)) that leaded me to a Ok status code response:

```diff
for(var i = 0; i < files.Length; i++)
{
	var file = files[i];
	var data = await file.Content();
-       body.Add(new ByteArrayContent(data), "file" + (i + 1), file.FileName);
+	var fileContent = new ByteArrayContent(data);
+       fileContent.Headers.Add("Content-Type", "application/octet-stream");
+       fileContent.Headers.Add("Content-Disposition", $"form-data; name=\"file\"; filename=\"{file.FileName}\"");
+       body.Add(fileContent, "file" + (i + 1), file.FileName);
}

+var boundaryValue = body.Headers.ContentType.Parameters.FirstOrDefault(p => p.Name == "boundary");
+if (boundaryValue != null)
+{
+    boundaryValue.Value = boundaryValue.Value.Replace("\"", string.Empty);
+}
```

The content headers looked to be mandatory. 
Also, bondary header also looks be generated as a Guid bad-formatted:
![image](https://github.com/calico-crusade/mangadex-sharp/assets/10831729/dec0e690-96d4-43ab-a9d8-b5817c74cac6)

Working properly:
![image](https://github.com/calico-crusade/mangadex-sharp/assets/10831729/286fa251-0e28-4ae9-80d5-b3477df0004d)

I didn't opened a PR because i don't know deeply if the lib is using some code pattern, or if there is any other endpoint that need this fix. If you don't mind about to fix it soon, I can read the whole repo code and open a PR this week. Otherwise I hope these info helps you to reproduce and fixing it :)

**Comment by calico-crusade** [comment]
I couldn't replicate the issue you're running into locally. But adding the missing configuration didn't break anything...
I've created a [pull-request](https://github.com/calico-crusade/mangadex-sharp/pull/4) that includes the changes using the proper C# header handlers and the suggested code above.

Let me know if these changes work for you, if they do, I'll merge the changes and publish a new version of the package for you!

**Comment by igorquintaes** [comment]
I just created a repro code [here](https://github.com/igorquintaes/MangaDexSharpErrorRepro). It returns same error in my win10 and alpine linux (dockerfile added). Now I will check with the PR changes, just a min.

**Comment by igorquintaes** [comment]
With your changes the code runs perfectly!

![image](https://github.com/calico-crusade/mangadex-sharp/assets/10831729/490b6038-ee39-49de-95f7-923a1cfa1d24)

**Comment by calico-crusade** [comment]
Great! I've merged the PR and updated the nuget package. Now we just have to wait for version 1.0.19 to index on [nuget](https://www.nuget.org/packages/MangaDexSharp#versions-body-tab) and you should be good.

If you run into any other issues, feel free to open an issue and I'll get to them as soon as possible. Thanks!
