### ISSUE TITLE
Default json serialization can't handle null properties as mangadex expect

### ISSUE THREAD

**Issue by igorquintaes** [calico-crusade/mangadex-sharp#5]
Hello again 👀 

After this issue, probably I won't need come here often hehe. I just ended to migrate my previous code to use mangadex-sharp (just a simple automation tool of QoL to scanlators groups, that I hope to release an open version soon...). But, well... Mangadex has some weird validations that I faced when tried to [commit a chapter upload](https://api.mangadex.org/docs/swagger.html#/Upload/commit-upload-session). Here we have a not-required property `chapterDraft.externalUrl`.

For example, it is a valid json :
```json
{
  "chapterDraft": {
    "volume": "1",
    "chapter": "86712254",
    "title": "string",
    "translatedLanguage": "cu-zt"
  },
  "pageOrder": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ]
}
```

... but it is an invalid json:
```json
{
  "chapterDraft": {
    "volume": "1",
    "chapter": "86712254",
    "title": "string",
    "translatedLanguage": "cu-zt",
    "externalUrl": null
  },
  "pageOrder": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ]
}
```

... and returns `Error validating /chapterDraft/externalUrl: NULL value found, but a string is required`.

MangaDex tries to validade a non-required property when it is present in request body and stop considering it as optional. Unfortunately, the default `JsonSerializerOptions` can't handle these scenarios, and we are unable to use some endpoints (in conditions that we don't have to fill null values) without overriding the default serializer options.

I solved it simply adding:

```csharp
services.AddJson(new JsonSerializerOptions()
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
})
```

But I think would be better if the default mangadex-sharp JsonSerializerOptions could be initialized using this settings.

**Comment by calico-crusade** [comment]
I’ll take a look at implementing this tomorrow. I also might switch to use a custom implementation of the `IJsonService` to avoid conflicts when used with other serialization systems, and I know that’s been an issue in the past. 

I’ll look into implementing this tomorrow morning (as it’s 11:30 PM here).

Also, feel free to open any PRs with these sorts of code changes that you want to see implemented. Even if they don’t follow my same coding style, I can just adjust or request changes to it as needed. I’ll see about adding a contributing guide at some point as well.

**Comment by calico-crusade** [comment]
I opened a PR that should address this change: #7 

Let me know if these changes work for you, and I'll merge them and release a new version.
This change also simplified the setup for MD# when using with dependency injection too, so that's an added bonus.
Also this includes your `DateTime?` PR changes in the versioned release of the package.

**Comment by igorquintaes** [comment]
I will check it soon. I am currently recovering from a covid infection

**Comment by calico-crusade** [comment]
I hope you feel better soon! I'll leave the PR and issue open until you have a chance to review the changes to ensure they work.

**Comment by igorquintaes** [comment]
Sorry the delay. I just checked it this morning and worked successfully. Thank you!
