### ISSUE TITLE
Required fields that accepts null values

### ISSUE THREAD

**Issue by igorquintaes** [calico-crusade/mangadex-sharp#8]
Hello again. Today I faced a new issue, but very similar than #7. 

We had some problems related to keep fields  with null value in sent json, right? Not I am facing a new error when a required field - that accepts null value - is not present in sent request, as example POST [/upload/{uploadSessionId}/commit](https://api.mangadex.org/docs/swagger.html#/Upload/commit-upload-session). There is required a `volume` field, but it can also be a null value. If we just exclude it from json, an error is returned and the operation is cancelled. 

```
400 - validation_exception - Error validating /chapterDraft/volume: The property volume is required
```

**Comment by calico-crusade** [comment]
I've committed a fix for this to the repo in a new branch. I don't have an easy way of testing the changes, so if you could let me know if it works: #9 

I've marked all of the other properties on the same post body object as "include if null" as well.

**Comment by igorquintaes** [comment]
Just tested it and now it is working, thank you!

**Comment by calico-crusade** [comment]
I've merged the changes and the new version is being validated on [nuget](https://www.nuget.org/packages/MangaDexSharp/1.0.21)
